# Move the prompt to a new line
add_newline = true

# The main prompt layout
format = """
$directory$git_branch$git_status$fill$cmd_duration$nodejs$golang$docker_context$python${env_var.HOSTNAME_LOCAL}${env_var.HOSTNAME_WORK}${env_var.HOSTNAME_REMOTE}${env_var.HOSTNAME_ROAM}$time
$character"""

[fill]
symbol = "─"
style = "#444444"

[directory]
style = "bold #00afaf"
truncate_to_repo = false
truncation_length = 8
format = "[$path]($style)[$read_only]($read_only_style)   "

[git_branch]
symbol = " "
style = "bold #5faf5f"

[git_status]
style = "bold #af5f5f"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[cmd_duration]
min_time = 500
style = "bold #ffcc00"
format = "took [$duration]($style) "

[time]
disabled = false
format = "at [$time](bold #888888) "
time_format = "%T"

[nodejs]
symbol = "󰎙 "
format = "[$symbol($version)](bold #5faf5f) "
detect_files = ["package.json", ".node-version", "nvmrc"]

[golang]
symbol = " "
format = "[$symbol($version)](bold #00ffff) "

[docker_context]
symbol = " "
format = "[$symbol($context)](bold #00aaff) "

[python]
symbol = " "
format = "[$symbol(${pyenv_prefix}${version})](bold #ffcc00) "

[hostname]
disabled = true

[env_var.HOSTNAME_LOCAL]
variable = "STARSHIP_HOSTNAME_LOCAL"
style = "bold #00ffff"
format = "[$env_value]($style) "

[env_var.HOSTNAME_WORK]
variable = "STARSHIP_HOSTNAME_WORK"
style = "bold #ffcc00"
format = "[$env_value]($style) "

[env_var.HOSTNAME_REMOTE]
variable = "STARSHIP_HOSTNAME_REMOTE"
style = "bold #ff5f5f"
format = "[$env_value]($style) "

[env_var.HOSTNAME_ROAM]
variable = "STARSHIP_HOSTNAME_ROAM"
style = "bold #5fffff"
format = "[$env_value]($style) "

[character]
success_symbol = "[❯](bold #00ff00)"
error_symbol = "[❯](bold #ff0000)"

[package]
disabled = true

[gcloud]
disabled = true
