[tools]
go = "latest"
node = "24"
starship = "latest"
zoxide = "latest"
fzf = "latest"
gh = "latest"
gcloud = "latest"
usage = "latest"
"npm:@google/gemini-cli" = "nightly"
chezmoi = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
